### ISSUE TITLE
Ruby 2.3.3, Rails 4.2 Disposable::Twin::Struct refers to ::Struct

### ISSUE THREAD

**Issue by saiqulhaq** [apotonick/disposable#69]
As the title of this issue

when I try to include Disposable::Twin::Struct module
Ruby raises error, because I am trying to include ::Struct class

I know that Disposable::Twin::Struct is deprecated, I should use Disposable::Twin::Property::Struct
but I couldn't require it, maybe because Disposable::Twin::Property::Struct is in the property.rb file  

so my gem unable to load it

```ruby
property :foo do
  include Disposable::Twin::Struct
end
```

```ruby
property :foo do
  include ::Disposable::Twin::Struct
end
```

all of the code above doesn't work

**Comment by saiqulhaq** [comment]
Sorry 
this is not a bug
this issue happened because documentation says to include Struct, not Property::Struct

![image](https://user-images.githubusercontent.com/1275215/36062030-d57668f8-0e96-11e8-9aff-771e8f4b85d6.png)

**Comment by apotonick** [comment]
Ok, thanks! We're in the process of rewriting all docs here: http://trailblazer.to/api-docs/

**Comment by saiqulhaq** [comment]
I have tried to clone your api-docs repo
but unable to run it on my laptop
is it still WIP?

**Comment by apotonick** [comment]
Yes!!!

**Comment by apotonick** [comment]
But @konung can help!

**Comment by konung** [comment]
Me <- to the rescue! 

@saiqulhaq  I pushed a change to Readme that explains how to set it up: https://github.com/trailblazer/api-docs#how-to-contribute-to-the-docs 

Ping me if  you run into specific problems, but the gist of it is that you also need local copies of all the gems to be able to build docs locallaly using middleman, because it uses tests from gems, directly to build examples.  ( This way they only need to be done once, and docs, get updated when gems get updated)

**Comment by saiqulhaq** [comment]
@konung I have tried it exactly you've mentioned on the gem
but there was an error with Torture gem

**Comment by konung** [comment]
hmm. We had another dev follow those instructions and they worked for him. Could be something specific to your setup?
What's the actual error?

**Comment by apotonick** [comment]
@saiqulhaq You have to pull the most recent `trailblazer-activity/master` to be up-to-date. :rocket:
